package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private int userId;
     private User user;
     private String name;
     private String street;
     private String buildingNumber;
     private String apartmentNumber;
     private String district;
     private boolean status;

    public Address() {
    }

	
    public Address(User user, String name, String street, String buildingNumber, String district, boolean status) {
        this.user = user;
        this.name = name;
        this.street = street;
        this.buildingNumber = buildingNumber;
        this.district = district;
        this.status = status;
    }
    public Address(User user, String name, String street, String buildingNumber, String apartmentNumber, String district, boolean status) {
       this.user = user;
       this.name = name;
       this.street = street;
       this.buildingNumber = buildingNumber;
       this.apartmentNumber = apartmentNumber;
       this.district = district;
       this.status = status;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getBuildingNumber() {
        return this.buildingNumber;
    }
    
    public void setBuildingNumber(String buildingNumber) {
        this.buildingNumber = buildingNumber;
    }
    public String getApartmentNumber() {
        return this.apartmentNumber;
    }
    
    public void setApartmentNumber(String apartmentNumber) {
        this.apartmentNumber = apartmentNumber;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


