package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean status;
     private Set provinces = new HashSet(0);

    public Country() {
    }

	
    public Country(String name) {
        this.name = name;
    }
    public Country(String name, Boolean status, Set provinces) {
       this.name = name;
       this.status = status;
       this.provinces = provinces;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(Set provinces) {
        this.provinces = provinces;
    }




}


