package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 09:30:54 PM by Hibernate Tools 4.3.1



/**
 * Creditcard generated by hbm2java
 */
public class Creditcard  implements java.io.Serializable {


     private int userId;
     private User user;
     private String name;
     private String credictardNumb;
     private String creditcardOwner;
     private String creditcardExpiration;
     private String creditcardSecurity;
     private boolean status;

    public Creditcard() {
    }

    public Creditcard(User user, String name, String credictardNumb, String creditcardOwner, String creditcardExpiration, String creditcardSecurity, boolean status) {
       this.user = user;
       this.name = name;
       this.credictardNumb = credictardNumb;
       this.creditcardOwner = creditcardOwner;
       this.creditcardExpiration = creditcardExpiration;
       this.creditcardSecurity = creditcardSecurity;
       this.status = status;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCredictardNumb() {
        return this.credictardNumb;
    }
    
    public void setCredictardNumb(String credictardNumb) {
        this.credictardNumb = credictardNumb;
    }
    public String getCreditcardOwner() {
        return this.creditcardOwner;
    }
    
    public void setCreditcardOwner(String creditcardOwner) {
        this.creditcardOwner = creditcardOwner;
    }
    public String getCreditcardExpiration() {
        return this.creditcardExpiration;
    }
    
    public void setCreditcardExpiration(String creditcardExpiration) {
        this.creditcardExpiration = creditcardExpiration;
    }
    public String getCreditcardSecurity() {
        return this.creditcardSecurity;
    }
    
    public void setCreditcardSecurity(String creditcardSecurity) {
        this.creditcardSecurity = creditcardSecurity;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


