package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1



/**
 * ExtratoppingId generated by hbm2java
 */
public class ExtratoppingId  implements java.io.Serializable {


     private int toppingextraId;
     private int orderId;
     private int itemId;

    public ExtratoppingId() {
    }

    public ExtratoppingId(int toppingextraId, int orderId, int itemId) {
       this.toppingextraId = toppingextraId;
       this.orderId = orderId;
       this.itemId = itemId;
    }
   
    public int getToppingextraId() {
        return this.toppingextraId;
    }
    
    public void setToppingextraId(int toppingextraId) {
        this.toppingextraId = toppingextraId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExtratoppingId) ) return false;
		 ExtratoppingId castOther = ( ExtratoppingId ) other; 
         
		 return (this.getToppingextraId()==castOther.getToppingextraId())
 && (this.getOrderId()==castOther.getOrderId())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getToppingextraId();
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getItemId();
         return result;
   }   


}


