package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1



/**
 * Extratopping generated by hbm2java
 */
public class Extratopping  implements java.io.Serializable {


     private ExtratoppingId id;
     private Orderitem orderitem;
     private Topping topping;
     private double price;

    public Extratopping() {
    }

    public Extratopping(ExtratoppingId id, Orderitem orderitem, Topping topping, double price) {
       this.id = id;
       this.orderitem = orderitem;
       this.topping = topping;
       this.price = price;
    }
   
    public ExtratoppingId getId() {
        return this.id;
    }
    
    public void setId(ExtratoppingId id) {
        this.id = id;
    }
    public Orderitem getOrderitem() {
        return this.orderitem;
    }
    
    public void setOrderitem(Orderitem orderitem) {
        this.orderitem = orderitem;
    }
    public Topping getTopping() {
        return this.topping;
    }
    
    public void setTopping(Topping topping) {
        this.topping = topping;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


