package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 09:30:54 PM by Hibernate Tools 4.3.1



/**
 * OrderitemId generated by hbm2java
 */
public class OrderitemId  implements java.io.Serializable {


     private int orderId;
     private int itemId;

    public OrderitemId() {
    }

    public OrderitemId(int orderId, int itemId) {
       this.orderId = orderId;
       this.itemId = itemId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderitemId) ) return false;
		 OrderitemId castOther = ( OrderitemId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getItemId();
         return result;
   }   


}


