package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 09:30:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String orderDate;
     private double total;
     private String paymentMethod;
     private String comment;
     private boolean status;
     private Set orderitems = new HashSet(0);

    public Order() {
    }

	
    public Order(User user, String orderDate, double total, String paymentMethod, boolean status) {
        this.user = user;
        this.orderDate = orderDate;
        this.total = total;
        this.paymentMethod = paymentMethod;
        this.status = status;
    }
    public Order(User user, String orderDate, double total, String paymentMethod, String comment, boolean status, Set orderitems) {
       this.user = user;
       this.orderDate = orderDate;
       this.total = total;
       this.paymentMethod = paymentMethod;
       this.comment = comment;
       this.status = status;
       this.orderitems = orderitems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getOrderitems() {
        return this.orderitems;
    }
    
    public void setOrderitems(Set orderitems) {
        this.orderitems = orderitems;
    }




}


