package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem  implements java.io.Serializable {


     private OrderitemId id;
     private Order order;
     private Pizza pizza;
     private String orderElementName;
     private boolean extraToppings;
     private double price;
     private String quantity;
     private boolean status;
     private Set extratoppings = new HashSet(0);

    public Orderitem() {
    }

	
    public Orderitem(OrderitemId id, Order order, Pizza pizza, String orderElementName, boolean extraToppings, double price, String quantity, boolean status) {
        this.id = id;
        this.order = order;
        this.pizza = pizza;
        this.orderElementName = orderElementName;
        this.extraToppings = extraToppings;
        this.price = price;
        this.quantity = quantity;
        this.status = status;
    }
    public Orderitem(OrderitemId id, Order order, Pizza pizza, String orderElementName, boolean extraToppings, double price, String quantity, boolean status, Set extratoppings) {
       this.id = id;
       this.order = order;
       this.pizza = pizza;
       this.orderElementName = orderElementName;
       this.extraToppings = extraToppings;
       this.price = price;
       this.quantity = quantity;
       this.status = status;
       this.extratoppings = extratoppings;
    }
   
    public OrderitemId getId() {
        return this.id;
    }
    
    public void setId(OrderitemId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Pizza getPizza() {
        return this.pizza;
    }
    
    public void setPizza(Pizza pizza) {
        this.pizza = pizza;
    }
    public String getOrderElementName() {
        return this.orderElementName;
    }
    
    public void setOrderElementName(String orderElementName) {
        this.orderElementName = orderElementName;
    }
    public boolean isExtraToppings() {
        return this.extraToppings;
    }
    
    public void setExtraToppings(boolean extraToppings) {
        this.extraToppings = extraToppings;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getExtratoppings() {
        return this.extratoppings;
    }
    
    public void setExtratoppings(Set extratoppings) {
        this.extratoppings = extratoppings;
    }




}


