package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pizza generated by hbm2java
 */
public class Pizza  implements java.io.Serializable {


     private Integer id;
     private String pizzaName;
     private String pizzaImage;
     private boolean status;
     private String categoryName;
     private Set pizzasizes = new HashSet(0);
     private Set orderitems = new HashSet(0);
     private Set toppings = new HashSet(0);

    public Pizza() {
    }

	
    public Pizza(String pizzaName, String pizzaImage, boolean status, String categoryName) {
        this.pizzaName = pizzaName;
        this.pizzaImage = pizzaImage;
        this.status = status;
        this.categoryName = categoryName;
    }
    public Pizza(String pizzaName, String pizzaImage, boolean status, String categoryName, Set pizzasizes, Set orderitems, Set toppings) {
       this.pizzaName = pizzaName;
       this.pizzaImage = pizzaImage;
       this.status = status;
       this.categoryName = categoryName;
       this.pizzasizes = pizzasizes;
       this.orderitems = orderitems;
       this.toppings = toppings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPizzaName() {
        return this.pizzaName;
    }
    
    public void setPizzaName(String pizzaName) {
        this.pizzaName = pizzaName;
    }
    public String getPizzaImage() {
        return this.pizzaImage;
    }
    
    public void setPizzaImage(String pizzaImage) {
        this.pizzaImage = pizzaImage;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getPizzasizes() {
        return this.pizzasizes;
    }
    
    public void setPizzasizes(Set pizzasizes) {
        this.pizzasizes = pizzasizes;
    }
    public Set getOrderitems() {
        return this.orderitems;
    }
    
    public void setOrderitems(Set orderitems) {
        this.orderitems = orderitems;
    }
    public Set getToppings() {
        return this.toppings;
    }
    
    public void setToppings(Set toppings) {
        this.toppings = toppings;
    }




}


