package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1



/**
 * Pizzasize generated by hbm2java
 */
public class Pizzasize  implements java.io.Serializable {


     private PizzasizeId id;
     private Pizza pizza;
     private Size size;
     private double precio;

    public Pizzasize() {
    }

    public Pizzasize(PizzasizeId id, Pizza pizza, Size size, double precio) {
       this.id = id;
       this.pizza = pizza;
       this.size = size;
       this.precio = precio;
    }
   
    public PizzasizeId getId() {
        return this.id;
    }
    
    public void setId(PizzasizeId id) {
        this.id = id;
    }
    public Pizza getPizza() {
        return this.pizza;
    }
    
    public void setPizza(Pizza pizza) {
        this.pizza = pizza;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


