package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privileges generated by hbm2java
 */
public class Privileges  implements java.io.Serializable {


     private Integer id;
     private boolean clientModule;
     private boolean adminModule;
     private boolean status;
     private Set roles = new HashSet(0);

    public Privileges() {
    }

	
    public Privileges(boolean clientModule, boolean adminModule, boolean status) {
        this.clientModule = clientModule;
        this.adminModule = adminModule;
        this.status = status;
    }
    public Privileges(boolean clientModule, boolean adminModule, boolean status, Set roles) {
       this.clientModule = clientModule;
       this.adminModule = adminModule;
       this.status = status;
       this.roles = roles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public boolean isClientModule() {
        return this.clientModule;
    }
    
    public void setClientModule(boolean clientModule) {
        this.clientModule = clientModule;
    }
    public boolean isAdminModule() {
        return this.adminModule;
    }
    
    public void setAdminModule(boolean adminModule) {
        this.adminModule = adminModule;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }




}


