package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean status;
     private Set pizzasizes = new HashSet(0);

    public Size() {
    }

	
    public Size(String name) {
        this.name = name;
    }
    public Size(String name, Boolean status, Set pizzasizes) {
       this.name = name;
       this.status = status;
       this.pizzasizes = pizzasizes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getPizzasizes() {
        return this.pizzasizes;
    }
    
    public void setPizzasizes(Set pizzasizes) {
        this.pizzasizes = pizzasizes;
    }




}


