package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 09:30:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Topping generated by hbm2java
 */
public class Topping  implements java.io.Serializable {


     private Integer id;
     private String name;
     private double price;
     private boolean canBeExtra;
     private boolean status;
     private Set extratoppings = new HashSet(0);
     private Set pizzas = new HashSet(0);

    public Topping() {
    }

	
    public Topping(String name, double price, boolean canBeExtra, boolean status) {
        this.name = name;
        this.price = price;
        this.canBeExtra = canBeExtra;
        this.status = status;
    }
    public Topping(String name, double price, boolean canBeExtra, boolean status, Set extratoppings, Set pizzas) {
       this.name = name;
       this.price = price;
       this.canBeExtra = canBeExtra;
       this.status = status;
       this.extratoppings = extratoppings;
       this.pizzas = pizzas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public boolean isCanBeExtra() {
        return this.canBeExtra;
    }
    
    public void setCanBeExtra(boolean canBeExtra) {
        this.canBeExtra = canBeExtra;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getExtratoppings() {
        return this.extratoppings;
    }
    
    public void setExtratoppings(Set extratoppings) {
        this.extratoppings = extratoppings;
    }
    public Set getPizzas() {
        return this.pizzas;
    }
    
    public void setPizzas(Set pizzas) {
        this.pizzas = pizzas;
    }




}


