package mx.tecmm.pizzas.vo;
// Generated 9/05/2018 11:04:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private Province province;
     private String name;
     private String lastName;
     private String secondLastName;
     private boolean status;
     private Creditcard creditcard;
     private Set orders = new HashSet(0);
     private Address address;

    public User() {
    }

	
    public User(Account account, Province province, String name, String lastName, String secondLastName, boolean status) {
        this.account = account;
        this.province = province;
        this.name = name;
        this.lastName = lastName;
        this.secondLastName = secondLastName;
        this.status = status;
    }
    public User(Account account, Province province, String name, String lastName, String secondLastName, boolean status, Creditcard creditcard, Set orders, Address address) {
       this.account = account;
       this.province = province;
       this.name = name;
       this.lastName = lastName;
       this.secondLastName = secondLastName;
       this.status = status;
       this.creditcard = creditcard;
       this.orders = orders;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getSecondLastName() {
        return this.secondLastName;
    }
    
    public void setSecondLastName(String secondLastName) {
        this.secondLastName = secondLastName;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Creditcard getCreditcard() {
        return this.creditcard;
    }
    
    public void setCreditcard(Creditcard creditcard) {
        this.creditcard = creditcard;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }




}


